- id: '1541502172425'
  alias: Mqtt RFID Music Player zurück
  trigger:
  - payload: '{"type":single_press}'
    platform: mqtt
    topic: stat/button_1/TYPE
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data:
      entity_id: media_player.marlon_zimmer
    service: media_player.media_previous_track
- id: button_1_double_press
  alias: 'Button #1 double press'
  trigger:
  - payload: '{"Counter1":2}'
    platform: mqtt
    topic: stat/button_1/RESULT
  condition:
  - condition: state
    entity_id: input_select.buttons
    state: aktiviert
  action:
  - data:
      entity_id: ' switch.marlon_deckenlampe'
    service: switch.toggle
- id: button_1_hold
  alias: Mqtt RFID Music Player button1 hold 2sec
  trigger:
  - payload: '{"type":hold_2sec}'
    platform: mqtt
    topic: stat/button_1/TYPE
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data:
      entity_id: script.marlon_schloss_switch
    service: script.turn_on
- id: button_2_skip
  alias: Mqtt RFID Music Player überspringen
  trigger:
  - payload: '{"type":single_press}'
    platform: mqtt
    topic: stat/button_2/TYPE
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data:
      entity_id: media_player.marlon_zimmer
    service: media_player.media_next_track
- id: button_2_hold
  alias: Mqtt RFID Music Player button2 hold 2sec
  trigger:
  - payload: '{"type":hold_2sec}'
    platform: mqtt
    topic: stat/button_2/TYPE
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data:
      entity_id: script.marlon_schloss_switch
    service: script.turn_on
- id: button_3_led
  alias: Mqtt RFID Music Player LED ausschaten
  trigger:
  - payload: '{"type":single_press}'
    platform: mqtt
    topic: stat/button_3/TYPE
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data:
      payload: '0'
      topic: /technight/Interface/PlayBox/color
    service: mqtt.publish
- id: button_3_hold
  alias: Mqtt RFID Music Player button3 help
  trigger:
  - payload: '{"type":hold_2sec}'
    platform: mqtt
    topic: stat/button_3/TYPE
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data:
      message: Help button activated plese help the MusicBox owner
      title: MusicBox help
    service: persistent_notification.create
  - data:
      message: Help button activated plese help the MusicBox owner
      target:
      - MarlonPC Firefox
      - Marlon Crome
      - MarlonPhone
      title: MusicBox help
    service: notify.html
- id: mqtt_rfid_rst
  alias: Mqtt RFID Music Player RST
  trigger:
  - payload: '2446736431'
    platform: mqtt
    topic: /technight/Interface/PlayBox
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data:
      entity_id: input_number.musikbox_rfid_resume
      value: '0'
    service: input_number.set_value
- id: mqtt_rfid_tag1
  alias: Mqtt RFID Music Player TAG1
  trigger:
  - payload: '2045822752'
    platform: mqtt
    topic: /technight/Interface/PlayBox
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data: {}
    service: script.mqtt_rfid_player_tag1_test0
  - data: {}
    service: script.mqtt_rfid_player_tag1_test1
- id: mqtt_rfid_tag2
  alias: Mqtt RFID Music Player TAG2
  trigger:
  - payload: '1228851232'
    platform: mqtt
    topic: /technight/Interface/PlayBox
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data: {}
    service: script.mqtt_rfid_player_tag2_test0
  - data: {}
    service: script.mqtt_rfid_player_tag2_test1
- id: mqtt_rfid_player_pause
  alias: Mqtt RFID Music Player Pause
  trigger:
  - payload: '1'
    platform: mqtt
    topic: /technight/Interface/PlayBox
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data:
      entity_id: media_player.marlon_zimmer
    service: media_player.media_pause
- id: '1545503941964'
  alias: Mqtt RFID Music Player next track
  trigger:
  - payload: 'ON'
    platform: mqtt
    topic: /technight/Interface/PlayBox/button
  condition:
  - condition: state
    entity_id: input_select.musikbox_rfid
    state: aktiviert
  action:
  - data:
      entity_id: media_player.marlon_zimmer
    service: media_player.media_next_track